### ISSUE TITLE
USB device not updating after printer's reboot

### ISSUE THREAD

**Issue by tholeb** [sbs20/scanservjs#505]
**Describe the bug**
When I restart my printer, the USB device path increments (e.g. `/dev/bus/usb/001/003` --> `/dev/bus/usb/001/004`) and the app doesn't track the changes, even when I reload the devices.

**To Reproduce**
1. Launch the app 
2. make sure the printer is on, and recognized in the app
3. reboot the printer (`lsusb` to see the new path)
4. Reload the devices on the app --> "No devices found"

**Expected behavior**
Reloading the device on the app should keep track of the new USB path

**Screenshots**
Before (device at 001:003):
![image](https://user-images.githubusercontent.com/43311443/209183642-1673be6b-7406-4bf9-bece-2b9e2cc7508d.png)

After printer reboot (no device found)
![image](https://user-images.githubusercontent.com/43311443/209180613-524e4102-bbda-487c-a712-f46e71bbb88d.png)

After container reboot (device at 001:004)
![image](https://user-images.githubusercontent.com/43311443/209184834-7044663a-cd11-4c9a-adcd-6f4f946f1152.png)

**Client (please complete the following information):**
 - Browser : chrome
 - Version : latest

**Server (please complete the following information):**
 - OS: Ubuntu 22.04 (rasp pi 4)
 - Node version : 18.12
 - NPM version 8.19
 - Docker version : podman version 3.4.4

**Logs**
```
node: v18.12.1
npm: 8.19.2
docker: podman version 3.4.4
DISTRIB_ID=Ubuntu; DISTRIB_RELEASE=22.04; DISTRIB_CODENAME=jammy; DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"; PRETTY_NAME="Ubuntu 22.04.1 LTS"; NAME="Ubuntu"; VERSION_ID="22.04"; VERSION="22.04.1 LTS (Jammy Jellyfish)"; VERSION_CODENAME=jammy; ID=ubuntu; ID_LIKE=debian; HOME_URL="https://www.ubuntu.com/"; SUPPORT_URL="https://help.ubuntu.com/"; BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"; PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"; UBUNTU_CODENAME=jammy

# Test using the following form:
# export SANED_NET_HOSTS="a|b" AIRSCAN_DEVICES="c|d" DELIMITER="|"; ./run.sh

# turn off globbing
set -f
+ set -f

# split at newlines only (airscan devices can have spaces in)
IFS='
'
+ IFS=


# Get a custom delimiter but default to ;
DELIMITER=${DELIMITER:-;}
+ DELIMITER=;

# Insert a list of net hosts
if [ ! -z "$SANED_NET_HOSTS" ]; then
  hosts=$(echo $SANED_NET_HOSTS | sed "s/$DELIMITER/\n/")
  for host in $hosts; do
    echo $host >> /etc/sane.d/net.conf
  done
fi
+ [ ! -z  ]

# Insert airscan devices
if [ ! -z "$AIRSCAN_DEVICES" ]; then
  devices=$(echo $AIRSCAN_DEVICES | sed "s/$DELIMITER/\n/")
  for device in $devices; do
    sed -i "/^\[devices\]/a $device" /etc/sane.d/airscan.conf
  done
fi
+ [ ! -z  ]

unset IFS
+ unset IFS
set +f
+ set +f

node ./server/server.js
+ node ./server/server.js
```

**Additional context**
The container settings (installed using [ansible](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html)):

```yml
containers.podman.podman_container:
    name: scanservjs
    image: sbs20/scanservjs:latest
    state: started
    recreate: true
    privileged: true
    restart: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      - "/home/pi/scans/images:/app/data/output"
      - "/home/pi/scans/config:/app/config"
    ports: "1025:8080"
    expose: 8080
    user: "0:1003"
    memory: "512m"
    generate_systemd:
      path: /etc/systemd/system
      no_header: true
      new: true
```

**Comment by sbs20** [comment]
What happens if you run `scanimage -L` inside the container?

**Comment by tholeb** [comment]
EDIT: added screenshots

**Comment by sbs20** [comment]
So it looks like it works after rebooting the container - yes?

My guess is it's docker that's not playing nice. All the app does is run `scanimage -L` - the app can't do anything else.

**Comment by tholeb** [comment]
![image](https://user-images.githubusercontent.com/43311443/209185712-dbf19feb-4b8a-4b43-8c72-dca3361cc88d.png)

**Comment by tholeb** [comment]
> So it looks like it works after rebooting the container - yes?
> 
> My guess is it's docker that's not playing nice. All the app does is run `scanimage -L` - the app can't do anything else.
> 
> Try to reproduce but run that command on both the container and host to see what's happening.
> 
> Consider a udev rule to fix the address of the device.

Yes it works after rebooting the container.

I'll look for the `udev` rule.



> I have to go out so won't reply for a bit. Do share your findings though - I'll write them up in documentation.

Thanks a lot for your (very) quick answers !

**Comment by tholeb** [comment]
I wrote the udev rule with my settings : `SUBSYSTEMS=="usb",KERNELS=="1-1.1",DRIVERS=="usb",ATTRS{idProduct}=="0827", ATTRS{idVendor}=="04b8", ATTRS{serial}=="L53010612130846360",SYMLINK+="%s{manufacturer}_printer"`

When I reboot the Pi, it works well, the symlink points to `/dev/usb/lp0`. But, when I unplug/plug the printer, the symlink now points to `/dev/sda` for some reason, even after a `udev` restart.

I changed the playbook with this:

```yml
containers.podman.podman_container:
    name: scanservjs
    image: sbs20/scanservjs:latest
    state: started
    recreate: true
    privileged: true
    restart: true
    device: "/dev/EPSON_printer:/dev/EPSON_printer:rw"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - "{{ scImages }}:/app/data/output"
      - "{{ scConfig }}:/app/config"
    ports: "1025:8080"
    expose: 8080
    user: "0:1003"
    memory: "512m"
```

The container is not updating after a printer's reboot. `scanimage -L` print the same output on the container, even thought the host does change the output.
