### ISSUE TITLE
Help please: "No devices found" after migration from Manjaro to Ubuntu

### ISSUE THREAD

**Issue by drewsed** [sbs20/scanservjs#528]
Hi,
I had a fine working docker installation on Manjaro linux. All I did was installing sane-airscan and starting the docker container with bind mount `/var/run/dbus` without `--privileged ` .

Now I migrated my installation to my Ubuntu server.  `scanimage -L` returns my printer the same way as on the old installation.

My compose script looks like this:
(part of my paperless-ngx stack)
```
scansrv:
    image: sbs20/scanservjs:latest
    restart: unless-stopped
    ports:
      - 8011:8080
    volumes:
      - /var/run/dbus:/var/run/dbus
      - consume:/app/data/output
```

On Ubuntu i have to add `privileged: true` to get it to work.
But I dont want a privileged container if there is a way without.

Any Ideas what I could do? Thanks in advance. I would like to provide more information if needed.

OS versions:
```
Linux NUCmanjaro 5.15.85-1-MANJARO #1 SMP PREEMPT Wed Dec 21 21:15:06 UTC 2022 x86_64 GNU/Linux
Linux nucubuntu 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

EDIT:
Is this related to Debian 11 issue?
