### ISSUE TITLE
Can't find scanner since I upgraded to latest (docker install)

### ISSUE THREAD

**Issue by MX10-AC2N** [sbs20/scanservjs#547]
Hi @sbs20 , first of all I would like to thank you for this ScanServJS which is very useful for me, I have been using it for several months with great satisfaction.

Yesterday I did a little update, I switched to the latest version of Docker `Docker version 23.0.0, build e92dd87` and I also updated the docker of Scanservjs.
But since impossible for Scanservjs to see my scanner connected in USB, I did not change anything to the parameters that I used previously where my surprise.
I tried some modifications but nothing makes it I can't see my scanner when I'm under Scanservjs...
Is there a problem ?
I have tried to run docker in "privileged" mode but even so I can't see my scanner. It worked fine before with my settings, so either I need one more setting with the new version, or there is a problem with the latest version of Docker.
Thanks again

Translated with www.DeepL.com/Translator (free version)

**Comment by edofullin** [comment]
Same issue here, it appears to be on version 2.25 since 2.24 works fine.
I have two scanners, one is detected without issue while the other is not detected anymore.

Entering the container with docker exec and running scanimage -L gets the correct result (the first is detected without issues, the second is not)

```
root@scannerwebgui:/app# scanimage -L
Created directory: /var/lib/snmp/cert_indexes
device `net:10.0.150.241:hpaio:/usb/Deskjet_F300_series?serial=CN739G42PC04KH' is a Hewlett-Packard Deskjet_F300_series all-in-one
device `net:10.0.30.140:smfp:usb;04e8;3469;ZF43B8KF3A0073N' is a Samsung M2070 Series on USB Scanner
```

**Comment by sbs20** [comment]
Are you in a position to pull [this branch](https://github.com/sbs20/scanservjs/tree/iss547) build the docker image and try it? This rolls back a recent dockerfile change which I'm hoping will fix the issue. If it does, I'll get it merged back in.

**Comment by edofullin** [comment]
> Are you in a position to pull [this branch](https://github.com/sbs20/scanservjs/tree/iss547) build the docker image and try it? This rolls back a recent dockerfile change which I'm hoping will fix the issue. If it does, I'll get it merged back in.

I tried but I get an error on an assertion related to DBus which also prevents running scanimage -L from the command line.
Rolling back to 2.24 the issue goes away

```
dbus[58]: arguments to dbus_connection_send() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3307.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)

```

Posting here my docker-compose just for reference, both my scanner are over the network.

```
version: "3"

services:
  scanservjs:
    container_name: scanservjs
    image: myscanservjs:pre2_25
#    image: sbs20/scanservjs:release-v2.24.0
    hostname: scannerwebgui
    restart: unless-stopped
    volumes:
      - "local_scans:/app/data/output"
      - "/mnt/config/scansevjs:/app/config"
    environment:
      SANED_NET_HOSTS: "10.0.30.140;10.0.150.241"
    networks:
      webservices:
        ipv4_address: 172.20.0.23
    labels:
      - "traefik.http.routers.scanner.tls.certresolver=henet"
      - "traefik.http.routers.scanner.tls.domains[0].main=XXXXX.net"
      - "traefik.http.routers.scanner.tls.domains[0].sans=*.XXXXXX.net"
      - "traefik.http.routers.scanner.rule=Host(`scanner.XXXXXX.net`)"
      - "traefik.http.routers.scanner.middlewares=lanonly@file"
      - "traefik.docker.network=webservices"
      - "traefik.enable=true"

volumes:
  scan_domain:
    external: true
  local_scans:
     external: true
  
    

networks:
  webservices:
    external: true
    name: webservices
```
